### ISSUE TITLE
Feature request: Separate appear and disappear animations for inline syntax

### ISSUE THREAD

**Issue by webserviceXXL** [jonhue/turbolinks-animate.js#22]
Maybe I missed this in your implementation but is there a way to set different appear and disappear animations with the inline syntax?

I'm using slideInRight and slideInLeft for a next and previous button. The animation to let disappear the current page is done with the data attributes you named in the README. But I can't find a way to override the default (from init) to set the appear animation of the new page.

**Comment by jonhue** [comment]
https://github.com/jonhue/turbolinks-animate.js#attributes

`data-turbolinks-animate-animation`: disappear animation
`data-turbolinks-animate-appear`: appear animation
