### ISSUE TITLE
adding data-turbolinks-animate-persist completely changes overall behaviour

### ISSUE THREAD

**Issue by vesper8** [jonhue/turbolinks-animate.js#5]
If I leave the defaults then the entire body fades completely in and out whethere I click a link or reload the whole browser.. working good so far

I would like to persist my navbar which is inside a <header> tag. So I added the persist option to it

```
<header data-turbolinks-animate-persist="true">
```

This breaks the behaviour. Now if I reload the whole browser (cmd-R) then it works, everything except the header properly fades in and out

but now if I use clicks from within the navbar then it doesn't work, the fade-in still works but the fade-out is completely gone

works on cmd-r, doesn't work on click

but without the persisted navbar, it works on both

For additional debugging I also tried

```
<header data-turbolinks-animate-persist-itself="header">
```

and even

```
<header data-turbolinks-animate-persist="false">
```

It seems like the very presence of any of these (even if set to false) on the header causes the fade-out animation to be skipped

any idea what could be wrong?

thanks!

**Comment by jonhue** [comment]
Could you provide a sample that reproduces the problem as I am using this feature in my applications and have not had any issues so far?

**Comment by jonhue** [comment]
@vesper8 

I found the issue - fixing it in 1.3.7
