### ISSUE TITLE
Documentation: emphasize need for importing Animate.css

### ISSUE THREAD

**Issue by nienkedekker** [jonhue/turbolinks-animate.js#8]
First off, thank you for your great library! It's really useful. However, reading the documentation, it wasn't clear to me that I had to manually import `animate.css` in my CSS. Animations weren't working until I added `@import '../../../node_modules/animate.css/animate.css'` to my master scss file.

Perhaps you could add this to your documentation! Cheers!

**Comment by jonhue** [comment]
Good call!
